# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: build
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node Tools'
    - script: which node

    - task: Npm@1
      displayName: 'Install Npm'
      inputs:
        workingDir: '$(System.DefaultWorkingDirectory)'
        command: install

    - task: Npm@1
      displayName: 'Build Application'
      inputs:
        workingDir: '$(System.DefaultWorkingDirectory)'
        command: custom
        customCommand: run-script build
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/build'
        ArtifactName: 'drop'
        publishLocation: 'Container'
        
- stage: Deploy
  displayName: Deploy static website to storage account
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: joellab2storage
    pool: 
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:            
          - task: AzureFileCopy@4
            inputs:
              SourcePath: '$(System.DefaultWorkingDirectory)/build'
              azureSubscription: 'Omegapoint Lab (d2245c54-7bbf-4a04-8b8c-e05622b29fc5)'
              Destination: 'AzureBlob'
              storage: 'joellab2storage'
              ContainerName: '$web'