# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage: build
  jobs:
  - job: build
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node Tools'
    - script: which node

    - task: Npm@1
      displayName: 'Install Npm'
      inputs:
        workingDir: '$System.DefaultWorkingDirectory'
        command: install

    - task: Npm@1
      displayName: 'Build Application'
      inputs:
        workingDir: '$System.DefaultWorkingDirectory'
        command: custom
        customCommand: run-script build
    - task: ArchiveFiles@2
      displayName: 'Archive build and copy to artifactStagingDirectory'
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)/build'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'