# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: build
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node Tools'
    - script: which node

    - task: Npm@1
      displayName: 'Install Npm'
      inputs:
        workingDir: '$(System.DefaultWorkingDirectory)'
        command: install

    - task: Npm@1
      displayName: 'Build Application'
      inputs:
        command: 'custom'
        workingDir: '$(System.DefaultWorkingDirectory)'
        customCommand: 'run-script build'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: $(System.DefaultWorkingDirectory)/build
        ArtifactName: 'drop'
        publishLocation: 'Container'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Omegapoint Lab (d2245c54-7bbf-4a04-8b8c-e05622b29fc5)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az storage blob service-properties update --account-name joellab2storage --static-website  --index-document index.html'
    - task: AzureCLI@2
      displayName: Copy build to static storage
      inputs:
        azureSubscription: 'Omegapoint Lab (d2245c54-7bbf-4a04-8b8c-e05622b29fc5)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az storage blob upload-batch -d "$web" --account-name joellab2storage -s "$(System.DefaultWorkingDirectory)/build"'

            
